--Find the names of students who improved their scores every single day (Day 3 > Day 2 AND Day 2 > Day 1). 
  Also, display the name of the Month they were born in using a date function.



--List the names and contact numbers of students who attended the Day 1 AND Day 2 exams, but EXCEPT those who showed up for Day 3.



--Find the students who registered in the Morning (before 12:00 PM) and scored higher than the average class score of Day 3.




--Create a master leaderboard. Combine the Hall Ticket Numbers and scores from all 3 days. 
  Use a CASE statement to label them: if the combined score across all 3 days is >120, they are a 'GOAT', otherwise 'Rising Legend'

